module Params

export DILITHIUM_MODE, N, Q, D, ROOT_OF_UNITY
export SEEDBYTES, CRHBYTES, TRBYTES, RNDBYTES
export POLYT1_PACKEDBYTES, POLYT0_PACKEDBYTES
export POLYVECH_PACKEDBYTES, POLYZ_PACKEDBYTES, POLYW1_PACKEDBYTES
export POLYETA_PACKEDBYTES
export CRYPTO_PUBLICKEYBYTES, CRYPTO_SECRETKEYBYTES, CRYPTO_BYTES
export K, L, ETA, TAU, BETA, GAMMA1, GAMMA2, OMEGA

const DILITHIUM_MODE = 2
const N = 256
const Q = 8380417
const D = 13
const ROOT_OF_UNITY = 1753
const SEEDBYTES = 32
const CRHBYTES = 48
const TRBYTES = 64
const RNDBYTES = 32
const K = 4
const L = 4
const ETA = 2
const TAU = 39
const BETA = 78
const GAMMA1 = (1 << 17)
const GAMMA2 = (Q - 1) ÷ 88
const OMEGA = 80
const POLYT1_PACKEDBYTES = 320
const POLYT0_PACKEDBYTES = 416
const POLYVECH_PACKEDBYTES = (OMEGA + K)
const POLYZ_PACKEDBYTES = 576
const POLYW1_PACKEDBYTES = 192
const POLYETA_PACKEDBYTES = 96
const CRYPTO_PUBLICKEYBYTES = SEEDBYTES + K * POLYT1_PACKEDBYTES
const CRYPTO_SECRETKEYBYTES = 2 * SEEDBYTES + CRHBYTES + L * POLYETA_PACKEDBYTES + K * POLYETA_PACKEDBYTES + K * POLYT0_PACKEDBYTES
const CRYPTO_BYTES = SEEDBYTES + L * POLYZ_PACKEDBYTES + POLYVECH_PACKEDBYTES

end
